name: Playwright CI

on:
  push:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t playwright-qa .

      - name: Run Tests in Container
        run: |
          # Add -t to see live console output in GitHub Actions
          docker run --name qa-runner playwright-qa

      - name: Extract Report and Traces
        if: always()
        run: |
          docker cp qa-runner:/app/report.html . || echo "Report not found"
          docker cp qa-runner:/app/test-results . || echo "Traces not found"

      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qa-test-results
          # This will upload both the HTML report and the trace folder
          path: |
            report.html
            test-results/